[package]
name = "miroir-cli"
version = "0.1.0"
authors = ["tadashi-aikawa <syou.maman@gmail.com>"]

[dependencies]
rusoto_core = "0.32.0"
rusoto_dynamodb = "0.32.0"
rusoto_s3 = "0.32.0"
docopt = "1"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"